url: "https://epiccraft.nl"
title: "EpicCraft Community"
slogan: "De Epische game Community van NL/BE"
description: "De Epische game Community van NL/BE"
permalink: /posts/:title:output_ext
year: 2024

navigation:
  - title: Home
    url: /
  - title: Archief
    url: /posts/

plugins:
  - jekyll-sitemap
